steps:
  - label: " :Build: build"
    command: echo "Build the rocket"
    key: build
  
  - label: " Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: " Deploy"
    command: echo " Launch the rocket"
    key: deploy
    depends_on: test
  
  - label: ":package: Package"
    command: tests.sh
    artifact_paths: "pkg/*"
    
